### ISSUE TITLE
M1 E 安卓7.0 不转发短信, 

### ISSUE THREAD

**Issue by verglas** [dss886/Transmis#4]
问题反馈：
1，能转发未接电(TG秒收)，但不能转发任何短信(TG_钉钉都没反应)
2，钉钉配置好，点击测试提示成功，收不到消息。钉钉机器人TOKEN没有问题。TG秒收。

另外 建议：
1，建议TG只填TOKEN不要填完整URL，比较麻烦。
2，建议填值的地方明码显示
3，建议添加企业微信群机器人
4，建议添加企业微信应用消息，因为TG要爱国。
5，建议短信和未接电来处添加一下测试。

谢谢。

**Comment by DrayChou** [comment]
我来回答一下建议1。
之所以需要填完整URL，是为了搭配TG接口代理，这样就不需要手机再去扶墙了。

**Comment by dss886** [comment]
1: 楼上已经回答了
2: 未来会增加切换显示选项
3-4: 暂无支持企业微信的计划，有兴趣可以帮忙贡献一下插件
5: 未来会支持

**Comment by dss886** [comment]
2：已支持 https://github.com/dss886/Transmis/commit/1d0e23363c1e394b2a10649d8739ea2fc27bd4b2
5：已支持 https://github.com/dss886/Transmis/commit/4330a16b2c08e2a59069e139d15607ef4c2ef987
